Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/', views.about,name = "about"),
    path('detail/<int:id>', views.detail,name = "detail"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path("info/",views.info,name = "info"),
    path("dashboard/",views.dashboard,name = "dashboard"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/",views.dashboard,name = "dashboard"),
    path("addarticle/",views.addArticle,name = "addarticle"),
    path("article/<int:id>",views.detail,name = "detail"),
    path("update/<int:id>",views.updateArticle,name = "update"),
    path("delete/<int:id>",views.deleteArticle,name = "delete"),
    path("",views.articles,name = "articles"),
    path("comment/<int:id>",views.addComment,name = "comment"),
    
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.register,name = "register"),
    path("login/",views.loginUser,name = "login"),
    path("logout/",views.logoutUser,name = "logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField



class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length=50,verbose_name = "Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date =models.DateTimeField(auto_now_add=True,verbose_name = "Oluşturma tarihi")
    article_image = models.FileField(blank=True,null = True,verbose_name = "Fotoğraf ekle")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Makale",related_name= "comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200,verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment_content
    class  Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms


class Loginform(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullancı Adı")
    password = forms.CharField(max_length = 20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label = "Parola(Tekrar)",widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolanız eşleşmiyor...")

        values = {
            "username" : username,
            "password" : password
        }
        return values

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

#Anasayfa URL
def index(request):
    context = {
        "numbers":[1,2,3,4,5,6]
        }

    return render(request,"index.html",context)

#Hakkımda URL
def about(request):
    return render(request,"about.html")

def detail(request,id):
    return HttpResponse("Detail:" + str(id))

@login_required(login_url= "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }

    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit = False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu...")
        return redirect("dashboard")

    return render(request,"addarticle.html",{"form":form}) 

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    
    comments = article.comments.all()
    
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url= "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit = False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi...")
        return redirect("dashboard")


    return render(request,"update.html",{"form":form})

@login_required(login_url= "user:login")
def deleteArticle(request,id):

    article = get_object_or_404(Article,id = id)
    article.delete()

    messages.success(request,"Makale başarıyla silindi...")

    return redirect("dashboard")
    


def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    

    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author,comment_content = comment_content)

        newComment.article = article

        newComment.save()
        
    return redirect(reverse("article:detail",kwargs={"id":id}))

def info(request):

    return render(request,"information.html")

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,Loginform
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import  login,authenticate,logout

def register(request):
    
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()  
        login(request,newUser)
        messages.success(request,"İşleminiz başarı ile gerçekleşti...")
            
        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)       
        

def loginUser(request):
    form = Loginform(request.POST or None)
    context = {
        "form" : form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)
        if user is None:
            messages.info(request,"Kullancı Adı veya Parola yanlış")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla giriş yaptınız...")
        login(request,user)
        return redirect("index")

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Çıkış işleminiz başarıyla gerçekleştirildi...")
    return redirect("index")

article/templates/about.html
{% extends "layout.html" %}

{% block body %}

<h2>Hakkımda</h2>
<hr>
<p>Merhaba ben Abdussamed ALTUNKAYA .Bunu yine yazdığımı bilmiyorum ama olsun adettendir .Bu benim 2.Python web site projem o yüzden pek bir şey yok fakat geliştireceğim.Sizin hepinizin özel bir yeri var çünkü benim ilk testerlarımsınız yani ilksiniz :) İyi eğlenceler...</p>



{% endblock body %}

article/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>

        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        
        <br>
        <button type = "submit" class = "btn btn-danger">Tamamla</button>

        </form>

    </div>
</div>


{% endblock  %}

article/templates/articles.html
{% extends "layout.html" %}

{% block body %}


<div class ="row" >
        <div class="col-md-10 offset-md-3" >
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
                </div>
        </div>
</div>

<div class = "row">
    <div class="col-md-10 offset-md-3" >
        <div class="col-lg-8">
            <form>
                {% csrf_token %}
                <input type="text" name = "keyword" class=" input-sm" maxlength="32" placeholder="Arama...">
                <button type="submit" class="btn btn-danger btn-sm">Ara</button>
            </form>
        </div>
    </div>

</div>



{% if articles %}

{% for article in articles %}

    <div class="row">
        <div class="col-md-10 offset-md-3">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>

        
        <hr>


        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}

        


        <!-- Post Content -->
        <p class="lead">{{article.content|safe|truncatewords:100}}</p>


        <hr>
        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <!-- Author -->
        <hr>
        <p class="lead"> 
          {{article.author.username}} tarafından yayınlandı.
        </p>

        <a style ="float : right;" href="{% url 'article:detail' article.id %}" class = "btn btn-info " >Devamını Oku...</a>

            </div>
        </div>
    </div>
       


{% endfor %}


{% else %}
<div class = "row">
    <div class="col-md-10 offset-md-3" >
        <div class="col-lg-8">
<div class = "alert alert-danger">
    Makale bulunamadı...
</div>
</div>
</div>
</div>

{% endif %}

{% endblock body %}

article/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldin,  <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>

{% if articles %}

    <table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">SİL</th>
    </tr>
  </thead>
  <tbody>

    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.id %}"class = "btn btn-danger">SİL</a></td>
    </tr>

    
    {% endfor %}
    
  </tbody>
</table>


{% else %}
  
  <div class = "alert alert-danger">Henüz makaleniz bulunmuyor...</div>

{% endif %}


{% endblock body %}

article/templates/detail.html
{% extends "layout.html" %}

{% block body %}

<!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>
        <hr>

        <!-- Date/Time -->
        <p>Yayın Tarihi: {{article.created_date}}</p>
        
        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}

        


        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p>

        <hr>
        
        <!-- Author -->
        
        <p class="lead">
          Yazar: {{article.author.username}} 
        </p>

        
        <hr>

        <!-- Yorum -->
        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
        {% for comment in comments  %}
         <div class = "media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="https://muratselek.com.tr/wp-content/uploads/2019/01/yorum-icon-avatar-men-50x50.png" alt="">
            <div class = media-body>
            <h6 class = "mt-0">{{comment.comment_author}}</h6>
            {{comment.comment_content}}<br>
            {{comment.comment_date}} 
            </div>
        </div>
        {% endfor %}


        {% else %}
        <div class = "alert alert-info">
        Bu makaleye herhangi bir yorum yazılmamış.İlk yorumu siz yapın.
        </div>
        {% endif %}

        
        <div class = "card my-4">
            <h5 class = "card-header">Yorum Ekle:</h5>
            <div class = "card-body">
            <form method = "post" action = "{% url 'article:comment' article.id %}">
              {% csrf_token %}
                <div class="form-group">
                  <label for="formGroupExampleInput">İsim:</label>
                  <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi giriniz...">
                </div>
              <div class = "form-group">
                <label for="formGroupExampleInput">Yorum:</label>
                <textarea name = "comment_content" class = "form-control" rows="3" placeholder= "Yorum giriniz..."></textarea>
              </div>
              <button type="submit" class = "btn btn-primary">Ekle</button>
            </form>
            
            </div>    
        </div>

    </div>

      </div> 



{% endblock body %}

article/templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <a class="navbar-brand" href="{% url 'index' %}">Anasayfa</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Hakkımda</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'info' %}">Bilgilendirme</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
        </li>
        <!-- Silmeyi unutma -->
        <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">Çıkış</a>
        </li>
      {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
        </li>
      {% endif %}

      </ul>

    </div>
  </nav>

article/templates/includes/posttemplates.html
<!-- Page Content -->
<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Post Title</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2019 at 12:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

        <blockquote class="blockquote">
          <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <footer class="blockquote-footer">Someone famous in
            <cite title="Source Title">Source Title</cite>
          </footer>
        </blockquote>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

article/templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class = "jumbotron text-center" >
        <h3>2.Python Web Site Projeme Hoşgeldiniz :)</h3>
        {% if request.user.is_authenticated %}
                <p>Hoşgeldin {{request.user.username}}</p>
        {% else %}
        {% endif %}
</div>



{% endblock body %}

article/templates/information.html
{% extends "layout.html" %}

{% block body %}

<h3>Sizden istediğim 5 şey</h3>
<hr>
<p>1:Kayıt ol.</p>
<p>2:Hakkımdaya gir.</p>
<p>3:Makale ekle. (Biliyorum henüz çok bir şey yok fakat web sitesi hakkında görüş bildiren bir makale eklersen çok mutlu olurum.)</p>
<p>4:Makaleler sayfasına gir ve harhangi bir makaleye yorum yap.</p>
<p>5:Ve son olarak en önemlisi eğer hata çıkarsa bana Whatsapp üzerinden ekran görüntüsünü at.</p>
<p>6:Eğer bunları yaparsan çok sevinirim şimdiden teşekkürler.</p>



{% endblock body %}

article/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Blog Proje 2</title>
</head>
<body>
    

    {% include "includes/navbar.html" %}
    <div  style = "margin-top : 100px; margin-bottom:100px" class = "container" >
        
        {% if messages %}
            
                {% for message in messages %}
                
                {% if message.tags == "info" %}
                <div  class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div  class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}

                    
                {% endfor %}
            
        {% endif %}

        {% block body %}
        
        {% endblock body %}
    
        </div>

    <script src= "{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src= "{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    

    
</body>
</html>

article/templates/login.html
{% extends "layout.html" %}


{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş yap</h3>
        <hr>

        <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

        </form>

    </div>
</div>



{% endblock body %}

article/templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>

        <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>

        </form>

    </div>
</div>


{% endblock body %}

article/templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelleme</h3>
        <hr>

        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        
        <br>
        <button type = "submit" class = "btn btn-danger">Güncelle</button>

        </form>

    </div>
</div>


{% endblock  %}